Complete the code to run it correctly
gri6ri/go_fitness_tracker_sprint_5 pull request #1
Opened 2023-11-22 12:15 UTC by Gri6ri

2023-11-23 19:23 UTC, robotomize requested changes
Классно! Все супер, но нужно добавить проверки с делением на 0

2023-11-23 19:23 UTC, robotomize commented on main.go
> +	return t.distance() / t.Duration.Hours() //
Не хватает проверки Duration на 0

2023-11-23 19:23 UTC, robotomize commented on main.go
> +	return s.distance() / float64(s.Duration.Hours())
Не хватает проверки Duration на 0

2023-11-24 11:23 UTC, Gri6ri commented on main.go
> +	return s.distance() / float64(s.Duration.Hours())
Спасибо, проверки добавил

2023-11-24 12:19 UTC, robotomize commented on main.go
> +	return s.distance() / float64(s.Duration.Hours())
Нужно отправить пулл реквест на ревью еще раз, чтобы я мог закрыть твою задачу

2023-11-24 14:40 UTC, robotomize approved these changes
Отличная работа! Принято

2023-12-22 16:12 UTC, closed without merging